---
title: "College Scorecard Data"
author: "Jiayuan Shi"
date: "November 07, 2015"
output: ioslides_presentation
runtime: shiny
---

## Shiny Presentation

This R Markdown presentation is made interactive using Shiny. The data comes from College Scorecard. It shows median earnings of students from Boston College, Boston University, Harvard University, Massachusetts Institute of Technology and Northeastern University, working in different years not enrolled after entry. 

The viewers of the presentation can change the assumptions of years not enrolled(10 years, 8 years or 6 years) and see the median earnings of students immediately. 

## Slide with Interactive Plot

```{r, echo=FALSE}
setwd("/Users/jiayuan/Documents/MA881/HW10/college")
mdearn <- read.csv("md_earn.csv",header=T)
inputPanel(
  selectInput("region", "Working Years Not Enrolled:", 
                    choices=colnames(mdearn[,2:4]), selected = colnames(mdearn[,2]) )
)

renderPlot({
   barplot(mdearn[,input$region], 
            main=input$region,
            ylab="Median Earnings of Students Working",
            xlab="College",
            names.arg = c("BC", "BU", "Harvard","MIT", "NU"))
})

```

## Conclusion
From the above barplots, we can see that the longer years a student is working, the higher earnings he or she will get. In addition, students from  Massachusetts Institute of Technology always have the highest income among the five colleges in Boston. 
